In [70]:
import numpy as np

In [71]:
a = np.array([2, 4, 6])

In [72]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [74]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.tile(2, (5, 3))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [76]:
np.repeat([1, 2], 5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [77]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [78]:
np.matrix('1, 2; 3, 4')

matrix([[1, 2],
        [3, 4]])

You can create a structured array as well

In [79]:
x = np.array([('a', 0.8), ('b', 0.2)], dtype=[('label', 'a8'), ('prob', 'f8')])

In [80]:
x['label']

array([b'a', b'b'], dtype='|S8')

In [81]:
x['prob']

array([0.8, 0.2])

Numpy's broadcasting allows us to vectorize operations like addition, subtraction etc.

In [82]:
a = np.array([2, 4, 6])
b = np.array([8, 10, 12])

In [83]:
a + b

array([10, 14, 18])

In [84]:
a + 1

array([3, 5, 7])

In [85]:
a - 9

array([-7, -5, -3])

In [86]:
a * 10

array([20, 40, 60])

Broadcasting vectorizes the operation so that it's as if the scalars 1, 9 and 10 we're repeated to form an array with the same dimensions as a to allow the operation.

Some rules for Numpy broadcasting

Taken from the Numpy documentation - <br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [87]:
a = np.arange(100).reshape(20, 5)
b = np.arange(20).reshape(20, 1)

In [88]:
a + b

array([[  0,   1,   2,   3,   4],
       [  6,   7,   8,   9,  10],
       [ 12,  13,  14,  15,  16],
       [ 18,  19,  20,  21,  22],
       [ 24,  25,  26,  27,  28],
       [ 30,  31,  32,  33,  34],
       [ 36,  37,  38,  39,  40],
       [ 42,  43,  44,  45,  46],
       [ 48,  49,  50,  51,  52],
       [ 54,  55,  56,  57,  58],
       [ 60,  61,  62,  63,  64],
       [ 66,  67,  68,  69,  70],
       [ 72,  73,  74,  75,  76],
       [ 78,  79,  80,  81,  82],
       [ 84,  85,  86,  87,  88],
       [ 90,  91,  92,  93,  94],
       [ 96,  97,  98,  99, 100],
       [102, 103, 104, 105, 106],
       [108, 109, 110, 111, 112],
       [114, 115, 116, 117, 118]])

Some broadcasting exercises

In [89]:
a = np.ones((9, 8, 1, 3, 3))
b = np.ones((1, 8, 9, 1, 3))

Can they be broadcasted?

In [90]:
a = np.ones((9, 1, 1))
b = np.ones((1, 9, 8))

Can they be broadcasted?

<br>Indexing

In [91]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
a[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [93]:
a = np.arange(25).reshape(5, 5, 1)

In [94]:
a

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [95]:
a[1, ...]

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [96]:
a[1, :, :]

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [97]:
a = a.squeeze()

In [98]:
a.shape

(5, 5)

In [99]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23],
        [24]]])

In [101]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
a[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

array([ 0,  6, 12, 18, 24])

In [103]:
x = a[0:2]

In [104]:
x[0, 0] = 100

In [105]:
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

What will the output of this be?

In [106]:
a[::2, [1, 3, 4]]

array([[ 1,  3,  4],
       [11, 13, 14],
       [21, 23, 24]])

What if you wanted to access elements in a cross product manner? <br>
eg. (0, 0), (0, 2), (0, 3), (2, 0), (2, 2), (2, 3)

In [107]:
np.ix_([0, 2], [0, 2, 3])

(array([[0],
        [2]]), array([[0, 2, 3]]))

In [108]:
a[np.ix_([0, 2], [0, 2, 3])]

array([[100,   2,   3],
       [ 10,  12,  13]])

Exerise time!

In [109]:
a = np.arange(25).reshape((5, 5))

In [110]:
b = np.arange(75).reshape((5, 5, 3))

* Add the two arrays together (remember the rules for broadcasting)
* Acess the first and last element of every alternate row

NumPy arrays are passed by reference

In [122]:
a = np.array([1, 2, 3, 4, 5])

In [123]:
b = a

In [124]:
b is a

True

In [125]:
np.may_share_memory(a, b)

True

In [126]:
a[1] = 100

In [127]:
print(a)

[  1 100   3   4   5]


In [117]:
print(b)

[  1 100   3   4   5]


In [128]:
b = np.array([1, 2, 3, 4, 5])

In [131]:
a = b.copy() # b[:]

In [132]:
a[1] = 9999

In [133]:
a

array([   1, 9999,    3,    4,    5])

In [134]:
b

array([1, 2, 3, 4, 5])

In [136]:
a = b[:]

In [137]:
a

array([1, 2, 3, 4, 5])

In [138]:
a[1] = 999

In [139]:
a

array([  1, 999,   3,   4,   5])

In [140]:
b

array([  1, 999,   3,   4,   5])

In [141]:
def func1(array):
    array *= 2
    return array

In [142]:
x = np.array([10])

In [143]:
y = func1(x)

In [144]:
y

array([20])

In [145]:
x

array([20])

In [148]:
def func2(array):
    array = array * 2
    return array

In [149]:
y = func2(x)

In [150]:
print(y)

[40]


In [151]:
x

array([20])

Behaviour is different for integers, floats etc.

In [156]:
x = 20

In [157]:
y = func2(x)

In [158]:
y

40

In [159]:
x

20