In [1]:
import numpy as np

For loops vs Numpy
<br>
Let's take a look at how Numpy's built in mathematical functions save us a lot of time by making looping redundant

In [2]:
#core/src/multiarray/ctors.c
%time x = np.arange(100000)
%time y = list(range(100000))

CPU times: user 1.04 ms, sys: 1.29 ms, total: 2.34 ms
Wall time: 1.04 ms
CPU times: user 3.27 ms, sys: 1.9 ms, total: 5.17 ms
Wall time: 5.2 ms


In [3]:
%time np.sum(x)

CPU times: user 299 µs, sys: 125 µs, total: 424 µs
Wall time: 322 µs


4999950000

In [4]:
%%time
total = 0
for _ in y:
    total += _

CPU times: user 17.1 ms, sys: 902 µs, total: 18 ms
Wall time: 17.2 ms


In [5]:
%%time
mean = np.average(x)

CPU times: user 655 µs, sys: 232 µs, total: 887 µs
Wall time: 563 µs


In [6]:
%%time 
total = 0
count = 0
for _ in y:
    total += _
    count += _
    
total / count

CPU times: user 38.9 ms, sys: 1.78 ms, total: 40.7 ms
Wall time: 39.7 ms


Which one do you think is faster?
<br>
abs(3.14159) or np.abs(3.14159)

In [7]:
%time abs(-3.14159)
%time np.abs(-3.14159)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 11 µs
CPU times: user 28 µs, sys: 1 µs, total: 29 µs
Wall time: 37.2 µs


3.14159

Now which one of these do you think is faster? <br>
abs([-1, 2, -3, -1, -4] or np.abs([-1, 2, -3, -1, -4])

In [8]:
%time [abs(x) for x in [-1, 2, -3, -1, -4] * 100]
%time np.abs([-1, 2, -3, -1, -4] * 100)

CPU times: user 62 µs, sys: 1 µs, total: 63 µs
Wall time: 68.9 µs
CPU times: user 123 µs, sys: 14 µs, total: 137 µs
Wall time: 145 µs


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Surprised? How about this

In [9]:
array = np.array([-1, 2, -3, -1, -4] * 100)
%time [abs(x) for x in array]
%time np.abs(array)

CPU times: user 602 µs, sys: 12 µs, total: 614 µs
Wall time: 620 µs
CPU times: user 25 µs, sys: 2 µs, total: 27 µs
Wall time: 35.8 µs


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Stride tricks with numpy. <br><br>
Sliding Window

In [10]:
a = np.arange(10)
s = 2
w = 4
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [12]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )[::s]

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

Short aside - <br>
`[::]` was added to Python at the request of the developers of Numerical Python, which uses the third argument extensively.

In [13]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [14]:
np.lib.stride_tricks.as_strided(a, shape = (15, 2, 2), strides = (8, 32, 8))[::2]

array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

Instead of striding using [::2], chagne the shape and strides in as_strided to create same effect.

In [15]:
np.lib.stride_tricks.as_strided(a, shape = (8, 2, 2), strides = (16, 32, 8))

array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

In [16]:
x = np.arange(10)

How do these arrays look in memory?

![alt text](NDArray_structure.png "NDArray Structure")

In [17]:
x.__array_interface__

{'data': (140654237035616, False),
 'descr': [('', '<i8')],
 'shape': (10,),
 'strides': None,
 'typestr': '<i8',
 'version': 3}

In [18]:
y = np.lib.stride_tricks.as_strided(x, shape = (9, 2), strides = x.strides * 2)

In [19]:
y.__array_interface__

{'data': (140654237035616, False),
 'descr': [('', '<i8')],
 'shape': (9, 2),
 'strides': (8, 8),
 'typestr': '<i8',
 'version': 3}

Einsum <br>
dot, diagonal, trace, sum, matrix multiplication

In [20]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

Return a view of the matrix

In [21]:
np.einsum('ij', A) 

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

In [22]:
A.view()

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

Matrix Transpose (doesn't work if you want to switch around axes in 3D etc.)

In [23]:
np.einsum('ji', A)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [24]:
A.T

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

Matrix Diagonal

In [25]:
%time np.einsum('ii->i', A)

CPU times: user 20 µs, sys: 1e+03 ns, total: 21 µs
Wall time: 27.2 µs


array([1, 2, 5])

In [26]:
%time np.diag(A)

CPU times: user 30 µs, sys: 12 µs, total: 42 µs
Wall time: 48.2 µs


array([1, 2, 5])

Matrix Trace

In [27]:
%time np.einsum('ii', A)

CPU times: user 49 µs, sys: 27 µs, total: 76 µs
Wall time: 83.2 µs


8

Sum along an axis <br> You try!

In [31]:
%time np.einsum('ij->i', A)
%time np.sum(A, axis=1)

CPU times: user 33 µs, sys: 0 ns, total: 33 µs
Wall time: 41 µs
CPU times: user 43 µs, sys: 1e+03 ns, total: 44 µs
Wall time: 50.1 µs


array([ 3,  6, 15])

Matrix and element-wise multiplication.

In [ ]:
A * B

In [ ]:
np.einsum('ij, ij -> ij', A, B)

In [ ]:
A @ B

In [ ]:
np.einsum('ij, jk-> ik', A, B)

In [ ]:
np.dot(A, B)

Using Einsum and stride tricks to do a convultion operation!

![alt text](arbitrary_padding_no_strides.gif "Convolution")

![alt text](2005-06-26-essence-of-images-convolution-matrix.png "Convolution")

In [ ]:
matrix = np.arange(25).reshape((5, 5))
print(matrix)

In [ ]:
conv_filter = np.array([[1, 1, 0], [1, 2, 3], [0, 1, 1]])
print(conv_filter)

In [ ]:
filter_shape = conv_filter.shape
conv_shape   = tuple(np.subtract(matrix.shape, filter_shape) + 1) + filter_shape
conv_strides = matrix.strides * 2
print(conv_shape)
print(conv_strides)

In [ ]:
sub_matrices = np.lib.stride_tricks.as_strided(matrix, conv_shape, conv_strides)

In [ ]:
print(matrix)
print(sub_matrices)

In [ ]:
convolved = np.einsum('ij, ijkl->kl', conv_filter, sub_matrices)

In [ ]:
print(convolved)

Exercise!

In [ ]:
a = np.arange(15)

* Window this array such that each window has 3 elements in it with a jump of 2 windows
* Find the row-wise mean of the last two elements in every alternate row.

(Answer - [7, 8])