In [4]:
import numpy as np

For loops vs Numpy
<br>
Let's take a look at how Numpy's built in mathematical functions save us a lot of time by making looping redundant

In [2]:
#core/src/multiarray/ctors.c
%time x = np.arange(100000)
%time y = list(range(100000))

CPU times: user 967 µs, sys: 1.09 ms, total: 2.06 ms
Wall time: 853 µs
CPU times: user 3.36 ms, sys: 1.91 ms, total: 5.26 ms
Wall time: 5.23 ms


In [5]:
%time np.sum(x)

CPU times: user 328 µs, sys: 160 µs, total: 488 µs
Wall time: 316 µs


4999950000

In [8]:
%%time
total = 0
for _ in y:
    total += _

CPU times: user 20.5 ms, sys: 688 µs, total: 21.2 ms
Wall time: 20.9 ms


In [9]:
%%time
mean = np.average(x)

CPU times: user 657 µs, sys: 273 µs, total: 930 µs
Wall time: 612 µs


In [10]:
%%time 
total = 0
count = 0
for _ in y:
    total += _
    count += _
    
total / count

CPU times: user 34.7 ms, sys: 1.59 ms, total: 36.3 ms
Wall time: 35.1 ms


Which one do you think is faster?
<br>
abs(3.14159) or np.abs(3.14159)

In [11]:
%time abs(-3.14159)
%time np.abs(-3.14159)

CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 11 µs
CPU times: user 25 µs, sys: 1 µs, total: 26 µs
Wall time: 31 µs


3.14159

Now which one of these do you think is faster? <br>
abs([-1, 2, -3, -1, -4] or np.abs([-1, 2, -3, -1, -4])

In [49]:
%time [abs(x) for x in [-1, 2, -3, -1, -4] * 100]
%time np.abs([-1, 2, -3, -1, -4] * 100)

CPU times: user 65 µs, sys: 0 ns, total: 65 µs
Wall time: 72 µs
CPU times: user 80 µs, sys: 1 µs, total: 81 µs
Wall time: 85.8 µs


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Surprised? How about this

In [50]:
array = np.array([-1, 2, -3, -1, -4] * 100)
%time [abs(x) for x in array]
%time np.abs(array)

CPU times: user 122 µs, sys: 0 ns, total: 122 µs
Wall time: 128 µs
CPU times: user 27 µs, sys: 1e+03 ns, total: 28 µs
Wall time: 37 µs


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Stride tricks with numpy. <br><br>
Sliding Window

In [53]:
a = np.arange(10)
s = 2
w = 4
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [55]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )[::s]

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

Short aside - <br>
`[::]` was added to Python at the request of the developers of Numerical Python, which uses the third argument extensively.

In [56]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [57]:
np.lib.stride_tricks.as_strided(a, shape = (15, 2, 2), strides = (8, 32, 8))[::2]

array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

Instead of striding using [::2], chagne the shape and strides in as_strided to create same effect.

In [58]:
np.lib.stride_tricks.as_strided(a, shape = (8, 2, 2), strides = (16, 32, 8))

array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

In [59]:
x = np.arange(10)

How do these arrays look in memory?

![alt text](NDArray_structure.png "NDArray Structure")

In [60]:
x.__array_interface__

{'data': (140416130682016, False),
 'descr': [('', '<i8')],
 'shape': (10,),
 'strides': None,
 'typestr': '<i8',
 'version': 3}

In [61]:
y = np.lib.stride_tricks.as_strided(x, shape = (9, 2), strides = x.strides * 2)

In [62]:
y.__array_interface__

{'data': (140416130682016, False),
 'descr': [('', '<i8')],
 'shape': (9, 2),
 'strides': (8, 8),
 'typestr': '<i8',
 'version': 3}

Einsum <br>
dot, diagonal, trace, sum, matrix multiplication

In [63]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

Return a view of the matrix

In [64]:
np.einsum('ij', A) 

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

In [65]:
A.view()

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

Matrix Transpose (doesn't work if you want to switch around axes in 3D etc.)

In [66]:
np.einsum('ji', A)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [67]:
A.T

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

Matrix Diagonal

In [29]:
%time np.einsum('ii->i', A)

CPU times: user 17 µs, sys: 0 ns, total: 17 µs
Wall time: 23.8 µs


array([1, 2, 5])

In [30]:
%time np.diag(A)

CPU times: user 30 µs, sys: 10 µs, total: 40 µs
Wall time: 45.8 µs


array([1, 2, 5])

Matrix Trace

In [31]:
%time np.einsum('ii', A)

CPU times: user 68 µs, sys: 36 µs, total: 104 µs
Wall time: 164 µs


8

Sum along an axis <br> You try!

In [32]:
%time np.einsum(' ', A) # np.sum(A, axis=1)

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

Matrix and element-wise multiplication.

In [33]:
A * B

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [34]:
np.einsum('ij, ij -> ij', A, B)

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [35]:
A @ B

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [36]:
np.einsum('ij, jk-> ik', A, B)

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [37]:
np.dot(A, B)

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

Using Einsum and stride tricks to do a convultion operation!

![alt text](arbitrary_padding_no_strides.gif "Convolution")

![alt text](2005-06-26-essence-of-images-convolution-matrix.png "Convolution")

In [38]:
matrix = np.arange(25).reshape((5, 5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [39]:
conv_filter = np.array([[1, 1, 0], [1, 2, 3], [0, 1, 1]])
print(conv_filter)

[[1 1 0]
 [1 2 3]
 [0 1 1]]


In [40]:
filter_shape = conv_filter.shape
conv_shape   = tuple(np.subtract(matrix.shape, filter_shape) + 1) + filter_shape
conv_strides = matrix.strides * 2
print(conv_shape)
print(conv_strides)

(3, 3, 3, 3)
(40, 8, 40, 8)


In [41]:
sub_matrices = np.lib.stride_tricks.as_strided(matrix, conv_shape, conv_strides)

In [82]:
print(matrix)
print(sub_matrices)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[[[ 0  1  2]
   [ 5  6  7]
   [10 11 12]]

  [[ 1  2  3]
   [ 6  7  8]
   [11 12 13]]

  [[ 2  3  4]
   [ 7  8  9]
   [12 13 14]]]


 [[[ 5  6  7]
   [10 11 12]
   [15 16 17]]

  [[ 6  7  8]
   [11 12 13]
   [16 17 18]]

  [[ 7  8  9]
   [12 13 14]
   [17 18 19]]]


 [[[10 11 12]
   [15 16 17]
   [20 21 22]]

  [[11 12 13]
   [16 17 18]
   [21 22 23]]

  [[12 13 14]
   [17 18 19]
   [22 23 24]]]]


In [46]:
convolved = np.einsum('ij, ijkl->kl', conv_filter, sub_matrices)

In [47]:
print(convolved)

[[ 62  72  82]
 [112 122 132]
 [162 172 182]]


Exercise!

In [48]:
a = np.arange(15)

* Window this array such that each window has 3 elements in it with a jump of 2 windows
* Find the row-wise mean of the last two elements in every alternate row.

(Answer - [7, 8])