In [ ]:
import numpy as np

For loops vs Numpy
<br>
Let's take a look at how Numpy's built in mathematical functions save us a lot of time by making looping redundant

In [ ]:
#core/src/multiarray/ctors.c
%time x = np.arange(100000)
%time y = list(range(100000))

In [ ]:
%time np.sum(x)

In [ ]:
%%time
total = 0
for _ in y:
    total += _

In [ ]:
%%time
mean = np.average(x)

In [ ]:
%%time 
total = 0
count = 0
for _ in y:
    total += _
    count += _
    
total / count

Which one do you think is faster?
<br>
abs(3.14159) or np.abs(3.14159)

In [9]:
%time abs(-3.14159)
%time np.abs(-3.14159)

CPU times: user 5 µs, sys: 1e+03 ns, total: 6 µs
Wall time: 11.9 µs
CPU times: user 24 µs, sys: 1e+03 ns, total: 25 µs
Wall time: 28.8 µs


3.14159

Now which one of these do you think is faster? <br>
abs([-1, 2, -3, -1, -4] or np.abs([-1, 2, -3, -1, -4])

In [10]:
%time [abs(x) for x in [-1, 2, -3, -1, -4] * 100]
%time np.abs([-1, 2, -3, -1, -4] * 100)

CPU times: user 64 µs, sys: 6 µs, total: 70 µs
Wall time: 77 µs
CPU times: user 83 µs, sys: 7 µs, total: 90 µs
Wall time: 95.1 µs


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Surprised? How about this

In [11]:
array = np.array([-1, 2, -3, -1, -4] * 100)
%time [abs(x) for x in array]
%time np.abs(array)

CPU times: user 139 µs, sys: 8 µs, total: 147 µs
Wall time: 153 µs
CPU times: user 20 µs, sys: 1 µs, total: 21 µs
Wall time: 26.9 µs


array([1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3,
       1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4,
       1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2,
       3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1,
       4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,
       2, 3, 1, 4, 1, 2, 3, 1, 4, 1, 2, 3, 1, 4, 1,

Stride tricks with numpy. <br><br>
Sliding Window

In [12]:
a = np.arange(10)
s = 2
w = 4
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8],
       [6, 7, 8, 9]])

In [14]:
np.lib.stride_tricks.as_strided(a, shape = (len(a) - w + 1, w), strides = a.strides * 2 )[::s]

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

Short aside - <br>
`[::]` was added to Python at the request of the developers of Numerical Python, which uses the third argument extensively.

In [15]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [16]:
np.lib.stride_tricks.as_strided(a, shape = (15, 2, 2), strides = (8, 32, 8))[::2]

array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

Instead of striding using [::2], chagne the shape and strides in as_strided to create same effect.

In [17]:
np.lib.stride_tricks.as_strided(a, shape = (8, 2, 2), strides = (16, 32, 8))

array([[[ 0,  1],
        [ 4,  5]],

       [[ 2,  3],
        [ 6,  7]],

       [[ 4,  5],
        [ 8,  9]],

       [[ 6,  7],
        [10, 11]],

       [[ 8,  9],
        [12, 13]],

       [[10, 11],
        [14, 15]],

       [[12, 13],
        [16, 17]],

       [[14, 15],
        [18, 19]]])

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

How do these arrays look in memory?

![alt text](NDArray_structure.png "NDArray Structure")

In [19]:
x.__array_interface__

{'data': (140641614568528, False),
 'descr': [('', '<i8')],
 'shape': (10,),
 'strides': None,
 'typestr': '<i8',
 'version': 3}

In [20]:
y = np.lib.stride_tricks.as_strided(x, shape = (9, 2), strides = x.strides * 2)

In [21]:
y

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [6, 7],
       [7, 8],
       [8, 9]])

In [22]:
y.__array_interface__

{'data': (140641614568528, False),
 'descr': [('', '<i8')],
 'shape': (9, 2),
 'strides': (8, 8),
 'typestr': '<i8',
 'version': 3}

Einsum <br>
dot, diagonal, trace, sum, matrix multiplication

In [24]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

Return a view of the matrix

In [27]:
np.einsum('ij -> i', A) 

array([ 3,  6, 15])

In [26]:
A.view()

array([[1, 1, 1],
       [2, 2, 2],
       [5, 5, 5]])

Matrix Transpose (doesn't work if you want to switch around axes in 3D etc.)

In [28]:
np.einsum('ij -> ji', A)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [29]:
A.T

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

Matrix Diagonal

In [30]:
%time np.einsum('ii->i', A)

CPU times: user 19 µs, sys: 1 µs, total: 20 µs
Wall time: 26 µs


array([1, 2, 5])

In [31]:
%time np.diag(A)

CPU times: user 29 µs, sys: 13 µs, total: 42 µs
Wall time: 48.2 µs


array([1, 2, 5])

Matrix Trace

In [33]:
%time np.einsum('ii -> ', A)

CPU times: user 49 µs, sys: 7 µs, total: 56 µs
Wall time: 66.8 µs


8

Sum along an axis <br> You try!

In [34]:
%time np.einsum('ij->i', A)
%time np.sum(A, axis=1)

CPU times: user 39 µs, sys: 1 µs, total: 40 µs
Wall time: 46.3 µs
CPU times: user 53 µs, sys: 0 ns, total: 53 µs
Wall time: 59.8 µs


array([ 3,  6, 15])

Matrix and element-wise multiplication.

In [35]:
A * B

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [36]:
np.einsum('ij, ij -> ij', A, B)

array([[0, 1, 0],
       [2, 2, 0],
       [5, 5, 5]])

In [37]:
A @ B

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [40]:
%time np.einsum('ij, jk-> ik', A, B)

CPU times: user 39 µs, sys: 0 ns, total: 39 µs
Wall time: 46 µs


array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [41]:
%time np.dot(A, B)

CPU times: user 26 µs, sys: 6 µs, total: 32 µs
Wall time: 39.8 µs


array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

Using Einsum and stride tricks to do a convultion operation!

![alt text](arbitrary_padding_no_strides.gif "Convolution")

![alt text](2005-06-26-essence-of-images-convolution-matrix.png "Convolution")

In [42]:
matrix = np.arange(25).reshape((5, 5))
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [43]:
conv_filter = np.array([[1, 1, 0], [1, 2, 3], [0, 1, 1]])
print(conv_filter)

[[1 1 0]
 [1 2 3]
 [0 1 1]]


In [45]:
filter_shape = conv_filter.shape
conv_shape   = tuple(np.subtract(matrix.shape, filter_shape) + 1) + filter_shape
conv_strides = matrix.strides * 2
print(conv_shape)
print(conv_strides)

(3, 3, 3, 3)
(40, 8, 40, 8)


In [55]:
sub_matrices = np.lib.stride_tricks.as_strided(matrix, conv_shape, conv_strides)

In [56]:
print(sub_matrices)

[[[[ 0  1  2]
   [ 5  6  7]
   [10 11 12]]

  [[ 1  2  3]
   [ 6  7  8]
   [11 12 13]]

  [[ 2  3  4]
   [ 7  8  9]
   [12 13 14]]]


 [[[ 5  6  7]
   [10 11 12]
   [15 16 17]]

  [[ 6  7  8]
   [11 12 13]
   [16 17 18]]

  [[ 7  8  9]
   [12 13 14]
   [17 18 19]]]


 [[[10 11 12]
   [15 16 17]
   [20 21 22]]

  [[11 12 13]
   [16 17 18]
   [21 22 23]]

  [[12 13 14]
   [17 18 19]
   [22 23 24]]]]


In [57]:
convolved = np.einsum('ij, ijkl->kl', conv_filter, sub_matrices)

In [58]:
print(convolved)

[[ 62  72  82]
 [112 122 132]
 [162 172 182]]


Exercise!

In [ ]:
a = np.arange(15)

* Window this array such that each window has 3 elements in it with a jump of 2 windows
* Find the row-wise mean of the last two elements in every alternate row.

(Answer - [7, 8])